name: Docker CI

on: [push]

jobs:

  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build the Docker image
      run: docker build . --tag csv-parser:${{ github.ref }}
    - name: Test
      run: |
        docker run csv-parser:${{ github.ref }} python -m pytest --cov=report
