name: Docker CI

on:
  push:
    branches:
      - develop
      - master

env:
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.repository.name }}

jobs:
  build_and_test_job:
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mlwarehouse_test
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
      - name: Run mypy against the image
        run: docker run --network host docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} mypy .
      - name: Run tests against the image
        run: docker run --network host docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} python -m pytest
      - name: Create test database and table and insert test data
        run: >-
          docker run
          --network host
          --env FLASK_APP=wrangler
          --env SETTINGS_PATH=config/test.py
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
          flask init-db
      - name: Login to regitry
        run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
      - name: Publish image with image tag being either develop/master/<tag_name>
        run: docker push docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
